// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/google/wire"
	config3 "github.com/yougroupteam/s-common-components/config"
	secretclient2 "github.com/yougroupteam/s-common-components/secretclient"
	"github.com/yougroupteam/u-common-components/apm"
	"github.com/yougroupteam/u-common-components/config"
	"github.com/yougroupteam/u-common-components/database"
	"github.com/yougroupteam/u-common-components/secretclient"
	"github.com/yougroupteam/u-common-components/storage/v4"
	config2 "github.com/yougroupteam/u-l10n/pkg/config"
	"github.com/yougroupteam/u-l10n/pkg/googleauth"
	"github.com/yougroupteam/u-l10n/pkg/repository"
	"github.com/yougroupteam/u-l10n/pkg/service/assetsvc"
	"github.com/yougroupteam/u-l10n/pkg/service/branchsvc"
	"github.com/yougroupteam/u-l10n/pkg/service/exportsvc"
	"github.com/yougroupteam/u-l10n/pkg/service/importsvc"
	"github.com/yougroupteam/u-l10n/pkg/service/keysvc"
	"github.com/yougroupteam/u-l10n/pkg/service/mergesvc"
	"github.com/yougroupteam/u-l10n/pkg/service/mrsvc"
	"github.com/yougroupteam/u-l10n/pkg/service/projectsvc"
	"github.com/yougroupteam/u-l10n/pkg/service/releasesvc"
	"github.com/yougroupteam/u-l10n/pkg/service/seed"
	"github.com/yougroupteam/u-l10n/pkg/service/tagsvc"
	"github.com/yougroupteam/u-l10n/pkg/service/usersvc"
	"github.com/yougroupteam/u-l10n/route"
)

// Injectors from inject_service.go:

func injectService(ctx context.Context) (*Service, error) {
	decodeOption := config.ProvideDecodeOption(ctx)
	configStore := config.ProvideConfigStoreImpl(ctx, decodeOption)
	configConfig, err := config2.ProvideConfig(configStore)
	if err != nil {
		return nil, err
	}
	apmConfig, err := apm.ProvideApmConfig(ctx, configStore)
	if err != nil {
		return nil, err
	}
	databaseConfig, err := database.ProvideDatabaseConfig(ctx, configStore)
	if err != nil {
		return nil, err
	}
	secretClient, err := secretclient.ProvideSecretClient(ctx)
	if err != nil {
		return nil, err
	}
	sqlConnector, err := database.ProvideSqlConnector(ctx, databaseConfig, secretClient, apmConfig)
	if err != nil {
		return nil, err
	}
	gormConnector, err := database.ProvideGORMConnector(ctx, databaseConfig, apmConfig, sqlConnector)
	if err != nil {
		return nil, err
	}
	localeRepository := repository.ProvideLocaleRepository(gormConnector)
	exportRowReader := repository.ProvideExportRowReader(gormConnector)
	service := exportsvc.ProvideService(localeRepository, exportRowReader)
	apiTokenRepository := repository.ProvideAPITokenRepository(gormConnector)
	releaseRepository := repository.ProvideReleaseRepository(gormConnector)
	transactional := database.ProvideTransactional(gormConnector)
	configDecodeOption := config3.ProvideDecodeOption(ctx)
	configConfigStore := config3.ProvideConfigStoreImpl(ctx, configDecodeOption)
	secretclientSecretClient, err := secretclient2.ProvideSecretClient(ctx)
	if err != nil {
		return nil, err
	}
	awsConfig, err := storage.ProvideAWSConfig(ctx, configConfigStore, secretclientSecretClient)
	if err != nil {
		return nil, err
	}
	storageStorage, err := storage.ProvideStorage(ctx, awsConfig)
	if err != nil {
		return nil, err
	}
	assetRepository := repository.ProvideAssetRepository(gormConnector)
	auditRepository := repository.ProvideAuditRepository(gormConnector)
	assetsvcService := assetsvc.ProvideService(transactional, storageStorage, assetRepository, auditRepository)
	verifier := googleauth.ProvideVerifier(configConfig)
	userRepository := repository.ProvideUserRepository(gormConnector)
	usersvcService := usersvc.ProvideService(transactional, userRepository, auditRepository)
	keyRepository := repository.ProvideKeyRepository(gormConnector)
	translationRepository := repository.ProvideTranslationRepository(gormConnector)
	branchRepository := repository.ProvideBranchRepository(gormConnector)
	tagRepository := repository.ProvideTagRepository(gormConnector)
	mergeRequestRepository := repository.ProvideMergeRequestRepository(gormConnector)
	keysvcService := keysvc.ProvideService(transactional, keyRepository, translationRepository, localeRepository, branchRepository, tagRepository, mergeRequestRepository, auditRepository)
	branchsvcService := branchsvc.ProvideService(transactional, branchRepository, auditRepository)
	mergesvcService := mergesvc.ProvideService(transactional, branchRepository, mergeRequestRepository, localeRepository, releaseRepository, exportRowReader)
	mrsvcService := mrsvc.ProvideService(transactional, branchRepository, mergeRequestRepository, localeRepository, mergesvcService, auditRepository)
	tagsvcService := tagsvc.ProvideService(transactional, tagRepository, auditRepository)
	releasesvcService := releasesvc.ProvideService(transactional, releaseRepository, localeRepository, exportRowReader, auditRepository)
	projectRepository := repository.ProvideProjectRepository(gormConnector)
	userProjectRoleRepository := repository.ProvideUserProjectRoleRepository(gormConnector)
	projectsvcService := projectsvc.ProvideService(transactional, projectRepository, userProjectRoleRepository, localeRepository)
	handler := route.ProvideHandler(configConfig, sqlConnector, service, apiTokenRepository, localeRepository, releaseRepository, assetsvcService, verifier, userRepository, usersvcService, keysvcService, branchsvcService, mrsvcService, tagsvcService, releasesvcService, projectsvcService)
	httpHandler := route.ProvideRoutes(apmConfig, configConfig, handler)
	seedService := seed.ProvideService(transactional, localeRepository, keyRepository, translationRepository)
	importsvcService := importsvc.ProvideService(transactional, localeRepository, keyRepository, translationRepository)
	mainService := &Service{
		Config:   configConfig,
		Handler:  httpHandler,
		Seed:     seedService,
		Tokens:   apiTokenRepository,
		Merge:    mergesvcService,
		Import:   importsvcService,
		Users:    usersvcService,
		Projects: projectsvcService,
	}
	return mainService, nil
}

// inject_service.go:

// commonWireSet holds the shared infrastructure providers. Feature packages
// get their own sets so this one stays the boring, stable part of the graph.
var commonWireSet = wire.NewSet(config.WireSet, apm.WireSet, secretclient.WireSet, database.WireSet, database.ProvideTransactional, config2.ProvideConfig, repository.WireSet, config3.WireSet, secretclient2.WireSet, storage.WireSet)
