// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/google/wire"
	"github.com/yougroupteam/u-common-components/apm"
	"github.com/yougroupteam/u-common-components/config"
	"github.com/yougroupteam/u-common-components/database"
	"github.com/yougroupteam/u-common-components/secretclient"
	config2 "github.com/yougroupteam/u-l10n/pkg/config"
	"github.com/yougroupteam/u-l10n/route"
)

// Injectors from inject_service.go:

func injectService(ctx context.Context) (*Service, error) {
	decodeOption := config.ProvideDecodeOption(ctx)
	configStore := config.ProvideConfigStoreImpl(ctx, decodeOption)
	configConfig, err := config2.ProvideConfig(configStore)
	if err != nil {
		return nil, err
	}
	apmConfig, err := apm.ProvideApmConfig(ctx, configStore)
	if err != nil {
		return nil, err
	}
	databaseConfig, err := database.ProvideDatabaseConfig(ctx, configStore)
	if err != nil {
		return nil, err
	}
	secretClient, err := secretclient.ProvideSecretClient(ctx)
	if err != nil {
		return nil, err
	}
	sqlConnector, err := database.ProvideSqlConnector(ctx, databaseConfig, secretClient, apmConfig)
	if err != nil {
		return nil, err
	}
	handler := route.ProvideHandler(configConfig, sqlConnector)
	httpHandler := route.ProvideRoutes(apmConfig, configConfig, handler)
	service := &Service{
		Config:  configConfig,
		Handler: httpHandler,
	}
	return service, nil
}

// inject_service.go:

// commonWireSet holds the shared infrastructure providers. Feature packages
// get their own sets so this one stays the boring, stable part of the graph.
var commonWireSet = wire.NewSet(config.WireSet, apm.WireSet, secretclient.WireSet, database.WireSet, config2.ProvideConfig)
